# Generated by Django 4.2.6 on 2025-09-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YandexMemberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', verbose_name='Имя и фамилия')),
                ('phone', models.TextField(default='', verbose_name='Номер телефона')),
                ('login', models.TextField(default='', verbose_name='Логин')),
                ('password', models.TextField(default='', verbose_name='Пароль')),
                ('proxy_string', models.TextField(default='', verbose_name='Прокси строка')),
                ('last_time', models.DateTimeField(verbose_name='Дата и время последнего обновления онлайна')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
            },
        ),
    ]
